### ISSUE TITLE
MeOS freezes when using services

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#11]
During our 2 day event, we used 2 services:
* Live Results to MeOS protocol (every 5sec)
* Automatic backup to USB flash drive (every 1min)

A small progress bar would appear in the top left corner, indicating that a service was executed.
Once in a while, such progress bar would take longer than expected, and freeze meos for a while. Thus we were unable to read results or do anything with MeOS.

Incresing Live Results service interval would decrese the amount of freezes, but not eliminate them.

**Comment by jmonclard** [comment]
I experienced similar effect last week-end while I was using the service to upload data to  https://liveresultat.orientering.se/.
Never happened to me while using the same service on a local server for screen display purpose. On this precise event I was running two services simultaneously on two different computers : one for arena display and a second one for Internet access. Only the remote access was unexpectedly long and seems to freeze MeOS. Restarting the service took as long as many minutes! Could be in relation to emmaupdate.php and not MeOS by itself.

**Comment by erikmelin** [comment]
Generally, you should use a separate instance of MeOS for services, since there is no multithreading for the services. If a task takes a long time, you wait.

In the next release, there will be improvements in the MOP protocol. Currently, the entire competition needs to be sent again when anything is deleted. This can take a significant time. With the updated protocol, this is no longer necessary.
