### ISSUE TITLE
Form loses focus on service execution

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#12]
Everytime a control has focus, it would loose it, if a service started to run. This makes it very hard to use forms, if services (like liveresults) are run very often (less than 15sec)

**Comment by erikmelin** [comment]
You should run services in a separate process. But obviously the behavior is not intentional.

**Comment by mariszin** [comment]
Is it possible to run multiple processes without using a MySQL database? If not, running services on events require much more complicated setup.

**Comment by mariszin** [comment]
Last week, during national cup, we did setup MeOS with MySQL, bet there seems to be some delay between updates of lists.
We setup a local MySQL 8 server, and 2 running MeOS instances - one for services, one  for readout.
Everything was fine, we could readout cards, and run services in the other instance.
But if we checked lists for newest results, they would not update, although in Competitors view we could see finish times for people - they would still not show up in the Latest Results list (or any other list for that matter).
Once disconnected and reconnected MeOs to MySQL, we would see the latest results, but it would still not update - only with a huge delay (1h+)

**Comment by erikmelin** [comment]
@mariszin I have heard of this issue a couple of times, but have never succeeded to understand what the problem is. Suspect are firewalls, Windows Defender, or other program trying to analyze and interfere with communication. I suggest you try to disable all such programs and see if the problem remains, or test another computer.

If you find out what the problem is, I would be grateful.

**Comment by erikmelin** [comment]
Registered a project to put writing to http on a separate thread.
