### ISSUE TITLE
Custom split form

### ISSUE THREAD

**Issue by vasyaabr** [melinsoftware/meos#14]
Hello!
Is it possible to customize split printing form (except fixed custom text)? If not, do you plan to add this feature?

**Comment by erikmelin** [comment]
The form now supports a class defined result module, and custom text with symbols. I consider this fixed.

**Comment by Paxy** [comment]
I kind of have the same question! Is there a way to customize the split printing format?
Couldn't find it in List Edit.
We need to enhance (bold) font size for splits in order to use splits with our thermal (Bixolon) printer. Currently, printing quality is so low that is hard to read. OEvent, OE and MT don't have the same issue as they use bigger fonts in splits.

**Comment by Paxy** [comment]
Ahh, I see, it's not customizable. Split format is defined in "TabSI::printCard" inside TabSI.cpp. It would be great if we could tweak the print font size a little bit from UI.
