### ISSUE TITLE
Cannot enter Id in runners database

### ISSUE THREAD

**Issue by mariszin** [melinsoftware/meos#46]
Why it is currently not possible to enter Id for runners? We want to use it as a registration number within our orienteering series.

**Comment by mariszin** [comment]
I am speaking about Runners database Id field, no Competitors External ID field.
![image](https://user-images.githubusercontent.com/518935/160831499-d0a943d7-bc42-4903-83b3-bb25192c8f66.png)

How is external ID filled from Runners database?

**Comment by kamilpipek** [comment]
When you import the runners database in IOF XML 3.0 and it contains the <Id> tags for runners the <Id> is imported into "External ID" field in MeOS. There could be more types of competitors <Id> in the imported IOF XML 3.0 and MeOS left you to choose which one should fulfill the "External ID". 
![220330-meos-idimport](https://user-images.githubusercontent.com/40379351/160834451-59c03c89-f93d-484f-bf6c-f0fb991f7fd6.jpg).

**Comment by mariszin** [comment]
Yes, I understand that I can add this number through import. But I cannot change it for a new entry.

**Comment by valdisj** [comment]
Ability to store Bib nr in RunnersDb or using RunnerID in Interactive readout. **Would it be possible, to add a possibility in the SI card reading dialogue (Interactive Readout) to enter "RunnerId", which is looking the runner who has this RunnerID associated up from Runner Database? (https://www.melin.nu/meos/en/show.php?base=3200&id=3211)**

Use case: We have a weekly competition, which runs each Wednesday. Competitors are having the Bib (or RunnerID) associated which is valid for this person for every single week. Not everyone has their private SI card. We have many beginners, to whom we are giving rent cards. Obviously, those are not associated with a person nor we are registering the person before the start due to a simplified start protocol (person comes, takes a map, get rent SI card, and off he/she goes into forest). When the competitor finishes, and if the competitor has not had a private SI card, we ask "What is your name?" Challenge is that  when there is a large flow of people in competition (>100) in a short time, we have challenges entering full name of the person after finish, even if he is registered in the runners DB. There is no problem with those, who have private ID cards, but we have >50% beginners, who usually use rent SI cards. It would be much easier, if we would be able to use "permanent Bibs" or "RunnerId", when he finishes to identify him. Currently, we cannot automatically use the RunnerID, since MeOS does not currently allow to enter RunnerID when person finishes, to have quick lookup in Runners DB and unique way to ID the person. 

The perfect dialogue at the finish line would be:

- Competitor finishes, comes to read SI card
- Enters SI card into the reader, MeOS finds the person from Runners DB, and if the SI card is registered to a particular person, result is registered, slip card is printed;
- If a SI card is not registered to a particular competitor (rent card, or a new never used card), we start entering RunnerID or Name of the Runner and MeOS finds this person from Runner DB.

**Comment by erikmelin** [comment]
@valdisj You can now manually change the external Id, and you can search for candidates using the Id when reading an unknown SI card.
