### ISSUE TITLE
[Feature suggestion] SPLITSanalysis uploader

### ISSUE THREAD

**Issue by Paxy** [melinsoftware/meos#47]
A suggestion for custom service that will automatically upload splits XML file to http://events.worldofo.com/woosplits.
Other than generating Winsplits result file, it needs to be URL-encoded and sent to the server.
Working PHP code for splits upload:
```
<?php
$file = file_get_contents('splits.xml', true);
$url=urlencode($file);
$data="data=".$url."&fileending=xml";

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,"http://events.worldofo.com/woosplits/uploadres.php");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,
            $data);

// Receive server response ...
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$server_output = curl_exec($ch);

curl_close ($ch);

$json=json_decode($server_output);

echo "http://events.worldofo.com/woosplits/?file=upload/".$json->name."\n";
?>
```

The response is URL to split analysis.

**Comment by erikmelin** [comment]
Thanks for the suggestion. I am afraid I will not built in support for this. Not because it is difficult, but because of future maintenance costs. It is already possible for MeOS to send IOF-XML (online results) to a web service (that could include the code you post) that could forward it to worldofo.
