### ISSUE TITLE
Journal of events

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#59]
During a running event, MeOS doesn't provide a mean to verify what has happened afterward: SICard reading, change of status of a runner, time fixing for a control, card number change, card pairing, etc. As to support the work of the referee, it would be good to keep a journal of all events - especially in client / server mode with several operators.

**Comment by erikmelin** [comment]
@pgaufillet Check out the new feature, which keeps track of manual changed made to card data; basically you can see if a card has been manipulated in any way.

Adding a rather low level log is possible, but I think it would be rather difficult to use. Creating a more human readable log is more difficult, and decisions need to be taken on what data to include, and since you can change data in so many ways (just supporting the runner form mode is not good enough). '

I have that on a list for possible future enhancements.
