### ISSUE TITLE
How to apply changes to several stages?

### ISSUE THREAD

**Issue by pgaufillet** [melinsoftware/meos#60]
In case of changes (card ID in particular) during a multi-stage event, how to apply them efficiently on several stages?

**Comment by kamilpipek** [comment]
Simply change the card ID on a competitors card and then confirm the dialog "Do you want to use the new card for all stages?".

**Comment by pgaufillet** [comment]
It works only if your db matchs some assumptions that are unclear, e.g. the runners have a (unique) external id, or their name and club loosely match from one stage to the other. It would be nice at least to clarify those assumptions in the documentation.

**Comment by erikmelin** [comment]
If you import entries to the first stage, and then use MeOS to create the following events, it will work.

If instead, you have separate entry for each stage, and ask MeOS to connect these events, then with external ID you get a pretty safe matching of competitors. Otherwise, as you note, the matching is based on name/club/card/age. But this is not 100% reliable. I do not think there is a waterproof solution if you have data of this type.
